  name: CI/CD Pipeline

  on:
    push:
      branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install 

      - name: Build React application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: build

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v2
          with:
            name: react-build
            path: ./react-build-temp 
        - name: Deploy to Server 1
          uses: easingthemes/ssh-deploy@main
          env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              REMOTE_HOST: ${{ secrets.SERVER_HOST }}
              REMOTE_USER: ${{ secrets.SERVER_USER }}
              TARGET: ${{ secrets.DEPLOY_PATH }}
        - name: Deploy build artifacts to Nginx
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
            
  
              # Start and enable Nginx
              sudo systemctl start nginx
              sudo systemctl enable nginx

              # Create the Nginx HTML directory if it doesn't exist
              sudo mkdir -p /var/www/html

              # Copy build artifacts to the Nginx HTML directory
              sudo rm -rf /var/www/html/*
              sudo cp -r /home/ubuntu/react/react-build-temp/* /var/www/html/
              # Restart nginx 
              sudo systemctl daemon-reload
              sudo systemctl reload nginx
              sudo systemctl restart nginx
              
